name: Android CI

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Java 17 for Android builds
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      # Android SDK
      - name: Set up Android SDK
        uses: android-actions/setup-android@v3

      - name: Accept licenses & install SDK packages
        run: |
          sdkmanager --licenses <<<'y'
          sdkmanager "platform-tools" "platforms;android-34" "build-tools;34.0.0"

      # Install a Gradle CLI for this job (since the repo has no wrapper yet)
      - name: Set up Gradle 8.7
        uses: gradle/actions/setup-gradle@v3
        with:
          gradle-version: 8.7

      # Generate the wrapper into the repo workspace
      - name: Generate Gradle Wrapper (8.7)
        run: gradle wrapper --gradle-version 8.7

      # Make wrapper script executable (Linux runner)
      - name: Make gradlew executable
        run: chmod +x ./gradlew

      # Build debug APK using the wrapper
      - name: Build Debug APK
        run: ./gradlew clean assembleDebug --no-daemon

      # Upload artifact
      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-debug
          path: app/build/outputs/apk/debug/app-debug.apk
